### ISSUE TITLE
Bug appeared in mapping reads step

### ISSUE THREAD

**Issue by Fishball99** [grenaud/vgan#1]
**1. What were you trying to do?**
I am testing if euka can run on my HPC, this is the command:
```
vgan euka -fq1 /data1/user/guest/wuyf/rotation/rawdata/20230928/1.preprocessing/DLTG001S1E1L1.1_eager_sheep/results/adapterremoval/output/DLTG001S1E1L1.1_1.fq_L0.pe.combined.fq.gz -t 30
```

**2. What did you want to happen?**
To get the correct output from euka.

**3. What actually happened?**
Got empty output files at all.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Stack trace path: /tmp/vg_crash_CENDpy/stacktrace.txt
```

**Comment by Fishball99** [comment]
Mapping reads...
warning:[vg giraffe] Attempting to set paired-end parameters but running in single-end mode
Guessing that /data1/apps/Vgan/vgan_v2.0.2-Miritillo/../share/vgan/euka_dir/euka_db.gg is GBWTGraph
Guessing that /data1/apps/Vgan/vgan_v2.0.2-Miritillo/../share/vgan/euka_dir/euka_db.gbwt is Giraffe GBWT
terminate called after throwing an instance of 'std::system_error'
  what():  Permission denied
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_CENDpy/stacktrace.txt
Please include the stack trace file in your bug report!
Number of fragments in input file: 0
Number of mapped fragments: 0
Number of fragments after filtering: 0
 .. done!
        -------------------------------
Abundance estimation completed!

**Comment by nicolaavogel** [comment]
Hi Wenqin Yu, 

The issue you see is most likely related to one of euka's graph files not having writing permission. 
In your folder ` /data1/apps/Vgan/vgan_v2.0.2-Miritillo/../share/vgan/euka_dir/ is a file called euka_db.dist`. This file needs to be writeable for everyone. Whoever installed and downloaded the files can make it writeable with `chmod a+w  /data1/apps/Vgan/vgan_v2.0.2-Miritillo/../share/vgan/euka_dir/euka_db.dist`. 

I hope this helps and solves your issue. Please feel free to reach out again if you have any more issues.

Best,
Nicola

**Comment by Fishball99** [comment]
Hi Nicola,

Thanks for your guide, I' ve told our server administrator change that permission of that file. Hope it works! :)
