### ISSUE TITLE
Unable to test vgan euka due to damageProfiles error

### ISSUE THREAD

**Issue by morien** [grenaud/vgan#2]
Hello, I'm trying to test euka out on some metagenomic shotgun sequencing samples. I set up according to instructions on my CentOS 8 remote server. The installed location of vgan is `/usr/bin/vgan`
The euka and hcfiles directories are here: `/usr/bin/share/vgan/`
Here's what the files look like in there. They are all owned by root and have chmod +w permissions
```
/usr/bin/share/vgan/
├── damageProfiles
│   └── none.prof
├── euka_dir
│   ├── euka_db.bins
│   ├── euka_db.clade
│   ├── euka_db.dist
│   ├── euka_db.gbwt
│   ├── euka_db.gfa
│   ├── euka_db.gg
│   ├── euka_db.giraffe.gbz
│   ├── euka_db_graph_path_supports
│   ├── euka_db.min
│   ├── euka_db.og
│   ├── euka_db.ry
│   ├── euka_db.snarls
│   └── euka_db.vg
└── hcfiles
    ├── children.txt
    ├── graph.dist
    ├── graph.gbwt
    ├── graph.gg
    ├── graph.giraffe.gbz
    ├── graph.og
    ├── graph_paths
    ├── graph.ry
    ├── graph.snarls
    ├── graph.xg
    ├── k17_w18.min
    ├── k31_w11.min
    ├── mappability.tsv
    ├── parents.txt
    ├── parsed_pangenome_mapping
    └── path_supports
```

here is the command I would like to run:
`vgan euka -fq1 ESW_7FEV_Library_control_36_S6_L003_R1_001.fq --euka_dir /usr/bin/share/vgan/euka_dir/`
this is the only output:
`libgab.h getFullPath failed on /usr/bin/../share/vgan/damageProfiles/none.prof`

Since I'm only running a test, not even trying to get damageProfiles info yet, I'm not sure why this error is popping up. Any help would be appreciated.

**Comment by nicolaavogel** [comment]
Hi morien,

All zero-damage profiles are read in by default, even if you do not specify the option. I can see that the way we specified the path for the damage profiles is not optimal (I will work on a better solution for this for our next update. Thank you.) For now, the easiest way to fix the error message would be to move the `share` folder out of your `bin` folder and one directory back into your `usr` folder. Then the specified path in euka should match the location of the `none.prof` damage profiles in the `damageProfiles` folder. 

Let me know if there are any more issues or if you have any more questions! 
Best, 
Nicola
