### ISSUE TITLE
Get blank image from plot_graph.R

### ISSUE THREAD

**Issue by Fishball99** [grenaud/vgan#3]
Hi developers,
I've met some problem when I run the scripts to visual the euka outputs. There are the command and errors.
It seems something wrong in data processing steps in painting inSize plot.

$ ~/share/vgan/plottingScripts/visualize_detected_taxa.sh euka_output
Loading required package: ggplot2
Error in `fortify()`:
! 'data' must be a <data.frame>, or an object coercible by 'fortify()', not a character vector.
Backtrace:
    ▆
 1. ├─ggplot2::ggplot(ne)
 2. └─ggplot2:::ggplot.default(ne)
 3.   ├─ggplot2::fortify(data, ...)
 4.   └─ggplot2:::fortify.default(data, ...)
 5.     └─cli::cli_abort(msg)
 6.       └─rlang::abort(...)
Execution halted

This is the image I got when I add a line to make ne a data frame. There is not a correct inSize plot.
`ne <- as.data.frame(df[-1, ])`
![euka_output_Ursidae](https://github.com/grenaud/vgan/assets/116473534/5ed34e27-de58-43d3-9c08-092e62e59887)

So I move to rstudio to see what happen. I saw the final format of ne is like this. 
![00e8ae64b56350ba8439c3a763089a1](https://github.com/grenaud/vgan/assets/116473534/1d588d1c-ab21-44c6-a7f3-3e46a6ad9da3)

Finally I  tried some simple lines of codes to get the figure (Surely it cannot read lines, there is just one line in my tsv). This is the figure, is it wright?
![frag](https://github.com/grenaud/vgan/assets/116473534/fb2c9a2c-3dea-426f-97f4-0dd2a7414957)

**Comment by nicolaavogel** [comment]
Hi Wenqin Yu, 

Thank you for reporting this issue. I fixed the code and updated the Rscript. Everything should be working now. 
If there are any other issues, please let us know. 

Best, 
Nicola
