### ISSUE TITLE
Soibean making subgraph error

### ISSUE THREAD

**Issue by Fishball99** [grenaud/vgan#4]
When I try the soibean make_graph_files.sh to make a Ursidae subgraph for downstream analysis, I met this error.

$ /data1/apps/Vgan/share/vgan/soibean_dir/make_graph_files.sh Ursidae
Using VG executable found in the current directory.
Processing input name: Ursidae

5th element: 6741214
6th element: 6756721
error:[vg chunk] unable to load graph / xg index file soibean_db.og
Subgraph created!
Building indexing files for subgraph ...
error[VPKG::load_one]: Correct input type not found in Ursidae_pre.vg while loading handlegraph::MutablePathDeletableHandleGraph
error[VPKG::load_one]: Correct input type not found in Ursidae.vg while loading handlegraph::PathHandleGraph
error[VPKG::load_one]: Correct input type not found in Ursidae.vg while loading handlegraph::PathHandleGraph
terminate called after throwing an instance of 'std::runtime_error'
  what():  GFAFile: Cannot memory map file Ursidae.gfa
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_3jgPLg/stacktrace.txt
Please include the stack trace file in your bug report!
error: [vg index] input is not a graph or GBZ
[vg minimizer] warning: --index-name is deprecated, use --output-name instead
[vg minimizer] error: input graph is not a GBZ, GBWTGraph, or HandleGraph.
chmod: cannot access ‘Ursidae.dist’: No such file or directory
... done!

Here is the directory of the soibean, it is readable and writable.

![image](https://github.com/grenaud/vgan/assets/116473534/41168545-cf17-40e6-ab36-f96b7f35ea22)

**Comment by nicolaavogel** [comment]
Hi, 

Thank you for raising this issue. I found the issue in the script and fixed the mistake. If you re-download the make_graph_files.sh file from https://raw.githubusercontent.com/grenaud/vgan/main/share/vgan/soibean_dir/make_graph_files.sh the script should run without an issue. 

Please let us know if you have any other issues or questions! 
Best, 
Nicola
