### ISSUE TITLE
euka reading error

### ISSUE THREAD

**Issue by Fishball99** [grenaud/vgan#5]
Hello developers,
I am running the test commands for the new version vgan, but I've met an error:
`$ vgan euka -fq1 three_dhigh_100.fq.gz -t 40`

` ___  __  __/ /______ _
 / _ \/ / / / /_/ __ `/
/  __/ /_/ / ,< / /_/ /
\___/\__,_/_/|_|\__,_/

Computing substitutions due to ancient damage:
[======================================================================] 100 %
.. done
Reading in taxa information ...
        -------------------------------
vgan: load.cpp:117: std::vector<Clade*>* Euka::load_clade_info(std::string, int): Assertion `tokens.size() == 6' failed.
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_tNKEVT/stacktrace.txt
Please include the stack trace file in your bug report!`

This is the content of stack trace file:
Crash report for vg not-from-git
Stack trace (most recent call last):
#8    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x4a0bdd, in
#7    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x128a48f, in
#6    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x493a77, in
#5    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x4ee8f7, in
#4    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x519eda, in
#3    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x129a835, in
#2    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x4917e3, in
#1    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x491913, in
#0    Object "/data1/apps/Vgan/vgan_v3.0.0-Fagiolo/vgan", at 0x11985fb, in

**Comment by nicolaavogel** [comment]
Hi, 

You see this error most likely because you are using the old version of euka_db.clade file. Please update this file to the new version, which you can find under in the share/euka_dir/ folder!

Best, 
Nicola
