### ISSUE TITLE
Long Runtime for GAM Loading

### ISSUE THREAD

**Issue by sean-at-biohaven** [grenaud/vgan#8]
After some test runs of Haplocart on FASTQ input, I was seeing runtimes of ~50 minutes on an AWS EC2 instance with 8 cores and 16Gb of RAM, with high-speed NVMe storage attached. When I reviewed the logs, I noticed that it takes almost 30 minutes to load (using the required graph files from the README), despite having high speed storage and sufficient resources on my instance. 

Is there any way to load this file more quickly? I'd like to run Haplocart on a large number of samples, so I'd like to lose as little time as possible just loading the reference. Alternatively, is there a way to process multiple FASTA/Q inputs, so that I only have to load the reference graph once? Could this step be skipped by pre-aligning my FASTQs via `giraffe` before running Haplocart?

Thank you very much for your help.

**Comment by JoshuaDanielRubin** [comment]
Hi Sean,

I see the issue has been closed - did you resolve the issue? I am surprised because the HaploCart graph is super tiny, it should take no time at all to load. 

Best,
Josh

**Comment by grenaud** [comment]
Hi Sean,
To add to Josh's comments. Just to be sure, this is loading the graph or mapping? 
Also is this ancient DNA or modern?

Gabriel
