### ISSUE TITLE
The binary version shows 2.0.0 instead of 2.0.1

### ISSUE THREAD

**Issue by spz1st** [grenaud/vgan#9]
When running the command "vgan version", the output is 2.0.0.

**Comment by JoshuaDanielRubin** [comment]
Hello, 

Thanks for raising the issue - I have just downloaded the static binary and "vgan version" gives 3.0.0 which is our latest. Are you referring to a previous version or have you compiled from source?

Best,
Josh

**Comment by JoshuaDanielRubin** [comment]
I will close for now - please reopen if still an issue.

**Comment by spz1st** [comment]
Hi Josh,

I just downloaded the binary labeled as version 2.0.1, but "vgan version"
gives 2.0.0.  I downloaded 2.0.1 because it's said 2.0.1 was the latest
stable one. But the binary I downloaded worked fine.

Thanks,
Shiping

**Comment by JoshuaDanielRubin** [comment]
Hi Shiping, 

On my end I see that our latest version is 3.0.0 (Fagiolo), can you confirm this on your end?

Best,
Josh

**Comment by spz1st** [comment]
Hi Josh,

I can see 3.0.0.  The reason I downloaded 2.0.1 is that 2.0.1 is the
only one labeled as verified (did you see it?).  Also if you download 2.0.1
and run "vgan version", what will you get?  I just downloaded it again
(wget https://github.com/grenaud/vgan/releases/download/v2.0.1/vgan) and
the command "vgan version" gave "vgan v2.0.0".

Thanks,
Shiping

**Comment by JoshuaDanielRubin** [comment]
Hi Shiping, 

Please do not worry about the green check (I don't even know how to generate that). The latest version 3.0.0 (Fagiolo) is the most up-to-date, so we would strongly suggest you use that one. There the version is correct in the binary.

Best,
Josh

**Comment by spz1st** [comment]
Okay.  Thanks.
